### ISSUE TITLE
New-GuestUserREST set AAA attribute list

### ISSUE THREAD

**Issue by UmbertoBernardi** [automate-this/public-scripts#1]
your script for the WLC-9800-cl is working great, but is missing the most important field, the AAA attribute list that must be assosciated to the guest user, to limit the connection to the right Wlan

**Comment by automate-this** [comment]
Seems you are right. This could be a problem if you have multiple guest wlans.

I can't find aaa attribute list in the corresponding yang model.
https://github.com/YangModels/yang/blob/main/vendor/cisco/xe/1791/Cisco-IOS-XE-native.yang

There is however a wlan-profile-name attribute:
```
      leaf wlan-profile-name {
        description
          "wlan-profile-name string with max 32 characters";
        type string;
      }
```

**Comment by UmbertoBernardi** [comment]
I saw the same, but unfortunately is not working... I've added the attribute but seems that the WLC is ignoring the wlan-profile-name

**Comment by automate-this** [comment]
Attribute not available in YANG model
